// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvu3IjKsyMCJEf1-0m4tKVp2freawFu8',
    appId: '1:1034388167715:web:fc6253698b1c8238fb6596',
    messagingSenderId: '1034388167715',
    projectId: 'rto-app-fed9b',
    authDomain: 'rto-app-fed9b.firebaseapp.com',
    storageBucket: 'rto-app-fed9b.firebasestorage.app',
    measurementId: 'G-FHQCN4F0N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPHowuldW2slxhuyJHLE90tAiJ16mddk',
    appId: '1:1034388167715:android:582cbcec803cc1cdfb6596',
    messagingSenderId: '1034388167715',
    projectId: 'rto-app-fed9b',
    storageBucket: 'rto-app-fed9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkBzMyQjU3wMNPrhHcM3a84Lo9rnakBkM',
    appId: '1:1034388167715:ios:605ec18e6d13d7e8fb6596',
    messagingSenderId: '1034388167715',
    projectId: 'rto-app-fed9b',
    storageBucket: 'rto-app-fed9b.firebasestorage.app',
    iosBundleId: 'com.example.rtoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkBzMyQjU3wMNPrhHcM3a84Lo9rnakBkM',
    appId: '1:1034388167715:ios:605ec18e6d13d7e8fb6596',
    messagingSenderId: '1034388167715',
    projectId: 'rto-app-fed9b',
    storageBucket: 'rto-app-fed9b.firebasestorage.app',
    iosBundleId: 'com.example.rtoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByvu3IjKsyMCJEf1-0m4tKVp2freawFu8',
    appId: '1:1034388167715:web:18e7c74c9ba5a34dfb6596',
    messagingSenderId: '1034388167715',
    projectId: 'rto-app-fed9b',
    authDomain: 'rto-app-fed9b.firebaseapp.com',
    storageBucket: 'rto-app-fed9b.firebasestorage.app',
    measurementId: 'G-EBXFLBWFDQ',
  );
}
